#!/bin/sh

#
# Installation script
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config files
MAIN_CONFIG=rnaseqload.config

# Make sure config file exists and source it
if [ -r ${MAIN_CONFIG} ]
then
    echo "Source ${MAIN_CONFIG}"
    . ${MAIN_CONFIG}
else
    echo "Cannot source configuration file: ${MAIN_CONFIG}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# Create the raw inputDir if it does not exist
#
if [ ! -d ${RAW_INPUTDIR} ]
then
    mkdir -p ${RAW_INPUTDIR}
fi

#
# Create the setload inputDir if it does not exist
#
if [ ! -d ${SET_INPUTDIR} ]
then
    mkdir -p ${SET_INPUTDIR}
fi

#
# Create the baseline input
#
if [ ! -d ${BASELINEINPUTDIR} ]
then
    mkdir -p ${BASELINEINPUTDIR}
fi

#
# Create the baseline output
#
if [ ! -d ${BASELINEOUTPUTDIR} ]
then
    mkdir -p ${BASELINEOUTPUTDIR}
fi

#
# Create the baseline raw inputDir if it does not exist
#
if [ ! -d ${BASELINERAW_INPUTDIR} ]
then
    mkdir -p ${BASELINERAW_INPUTDIR}
fi

exit 0
